---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: adzerk/boot-clj
    tag: "latest"

inputs:
  - name: metalib

outputs:
  - name: metalib-build

run:
  dir: metalib/docs
  run:
    path: /bin/bash
    args:
    - metalib/docs/ci/commit.sh


